version: '2'
services:
  service-b:
    image: 820537372947.dkr.ecr.us-east-1.amazonaws.com/service-b
    ports:
    - 8080:8080
    environment:
      AWS_XRAY_DAEMON_ADDRESS:
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/service-b
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs
  x-ray:
    image: amazon/aws-xray-daemon 
    ports:
    - 2000:2000/udp
    environment:
      AWS_XRAY_DAEMON_ADDRESS:
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/service-b
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs
