version: '2'
services:
  service-a:
    image: 820537372947.dkr.ecr.us-east-1.amazonaws.com/service-a
    ports:
    - 8080:8080
    environment:
      API_CNAME: skoXray-LB-420401958.us-east-1.elb.amazonaws.com
      AWS_XRAY_DAEMON_ADDRESS:
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/service-a
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs
  x-ray:
    image: amazon/aws-xray-daemon
    ports:
    - 2000:2000/udp
    environment:
      AWS_XRAY_DAEMON_ADDRESS:
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/service-a
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs
